# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DemoApp < Formula
  desc "Go CI Demo App showcasing goreleaser, Github Actions and ko."
  homepage "https://github.com/embano1/ci-demo-app/blob/master/README.md"
  version "0.3.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.3.1/demo-app_Darwin_x86_64.tar.gz"
    sha256 "191c21b0016a9c135844bcbbd5f635974169d6edaf343feeb70c1790106f07cd"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.3.1/demo-app_Darwin_arm64.tar.gz"
    sha256 "ec3d4ffa5d19f191b02621ddcc934ad638b5b145fc092e42a09bab8fb3b10319"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.3.1/demo-app_Linux_x86_64.tar.gz"
    sha256 "b02d0be7d369b09d64d63fdc9dbd3684f8d73b61752eb5a462545e8a84e4b3f7"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.3.1/demo-app_Linux_armv6.tar.gz"
    sha256 "b87fcae3c2f115deaa2188812402286cac00dbb8d0afa27e12401f34dc67bafb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.3.1/demo-app_Linux_arm64.tar.gz"
    sha256 "3e613dc575a6dc9679d0b92a8d266aeb6a813f5dbe85465f4904b15ef7816544"
  end

  def install
    bin.install "demo-app"
  end

  test do
    system "#{bin}/demo-app version"
  end
end
