# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DemoApp < Formula
  desc "Go CI Demo App showcasing goreleaser, Github Actions and ko."
  homepage "https://github.com/embano1/ci-demo-app/blob/master/README.md"
  version "0.2.9"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.2.9/demo-app_Darwin_x86_64.tar.gz"
    sha256 "354addaa6e4e3c2e59caac61480bab2275e02ffbe9652b7eb2b89b7ec5f8de6d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.2.9/demo-app_Darwin_arm64.tar.gz"
    sha256 "4cdfe66c9d64b98ed6564e6c015d1cade5deb1558bf242b8ad786ef37368e650"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.2.9/demo-app_Linux_x86_64.tar.gz"
    sha256 "b7606c5cc1f2cde97cf22843ee353722f1c37b9f31f1a616389b2ec74bfa6776"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.2.9/demo-app_Linux_armv6.tar.gz"
    sha256 "85a4cda509e7248aba159c9347d198fffa3a6b201f5b79758bd61d1d5335dcb9"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/embano1/ci-demo-app/releases/download/v0.2.9/demo-app_Linux_arm64.tar.gz"
    sha256 "621aa595a8b0f469a39c03ffcd938fb84555992e9df38745841df6a9acb96993"
  end

  def install
    bin.install "demo-app"
  end

  test do
    system "#{bin}/demo-app version"
  end
end
